sudo: false

language: rust
rust: nightly

os:
  - osx
  - linux

cache:
  cargo: true

install:
  - rustup component add rustfmt-preview
  - cargo install clippy --force

script:
  - cargo fmt --all -- --check
  - cargo clippy
  - cargo build
  - cargo test
