jobs:

- job: check_formatting
  displayName: Check formatting
  pool:
    vmImage: ubuntu-16.04
  steps:
    - script: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        $HOME/.cargo/bin/rustup component add rustfmt clippy
      displayName: Install stable Rust
    - script: |
        $HOME/.cargo/bin/cargo fmt --all -- --check
      displayName: Run rustfmt
    - script: |
        $HOME/.cargo/bin/cargo clippy --all
      displayName: Run clippy
- template: _build/azure-pipelines-template.yml
  parameters:
    name: Linux
    target: x86_64-unknown-linux-gnu
    vmImage: ubuntu-16.04

- template: _build/azure-pipelines-template.yml
  parameters:
    name: macOS
    target: x86_64-apple-darwin
    vmImage: macOS-10.13

- template: _build/azure-pipelines-template.yml
  parameters:
    name: Windows
    target: x86_64-pc-windows-msvc
    vmImage: vs2017-win2016
