[package]
name = "pgp"
version = "0.1.0"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]
description = "PGP implementation in Rust"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/dignifiedquire/pgp"
repository = "https://github.com/dignifiedquire/pgp"

keywords = ["pgp", "gpg", "pretty good privacy", "email", "encryption", "privacy"]

[dependencies]
rsa = { git = "https://github.com/dignifiedquire/rust-rsa", branch = "master" }
num-bigint = { git = "https://github.com/dignifiedquire/num-bigint", branch = "master" }
crc24 = "^0.1"
base64 = "^0.9"
byteorder = "^1.2"
enum_primitive = "^0.1"
chrono = "^0.4"
failure = "^0.1"
circular = "^0.2"
itertools = "^0.7"
sha-1 = "^0.8"
sha2 = "^0.8"
md-5 = "^0.8"
ripemd160 = "^0.8"
generic-array = "^0.12"
digest = "^0.8"
aes = "^0.3"
blowfish = "^0.3"
twofish = "^0.1"
des = "^0.1"
block-modes = "^0.2"
hex = "^0.3"
cfb-mode = "^0.3"
flate2 = { version = "1.0.4", default-features = false, features = ["rust_backend"] }
num-derive = "0.2.3"
num-traits = "0.2.6"
cast5 = { git = "https://github.com/dignifiedquire/block-ciphers", branch = "cast5" }
x25519-dalek = { version = "0.3", default-features = false, features = ["std", "u64_backend"] }
lazy_static = "1.2.0"
block-padding = "0.1.2"

[dependencies.nom]
version = "^4.0"

[dev-dependencies]
rand = "0.5.5"
hex-literal = "^0.1"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
glob = "^0.2"

[features]
default = []
nightly = ["x25519-dalek/nightly"]
