[package]
name = "pgp"
version = "0.3.1"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]
description = "OpenPGP implementation in Rust"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/rpgp/rpgp"
repository = "https://github.com/rpgp/rpgp"
readme = "README.md"

keywords = ["pgp", "gpg", "openpgp", "email", "encryption"]
categories = ["cryptography", "std", "email"]

exclude = ["tests/tests/*"]

edition = "2018"

[dependencies]
crc24 = "^0.1"
base64 = "^0.10.1"
byteorder = "^1.2"
enum_primitive = "^0.1"
chrono = "^0.4"
failure = "^0.1"
circular = "^0.3"
sha-1 = "^0.8"
sha2 = "^0.8"
md-5 = "^0.8"
ripemd160 = "^0.8"
generic-array = "^0.12"
digest = "^0.8"
aes = "^0.3"
blowfish = "^0.4"
twofish = "^0.2"
des = "^0.3"
block-modes = "^0.3"
hex = "^0.4"
cfb-mode = "^0.3.2"
num-derive = "0.2.3"
num-traits = "0.2.6"
lazy_static = "1.2.0"
block-padding = "0.1.2"
log = "0.4.6"
try_from = "^0.3"
derive_builder = "0.7.0"
bitfield = "0.13.1"
sha3 = "0.8.1"
rand = "0.6"
smallvec = "0.6.9"
cast5 = "0.6.0"
rsa = "^0.1.4"
nom = "^4.2"
zeroize = { version = "0.10.1", features = ["zeroize_derive"] }
clear_on_drop = { version = "0.2.3", features = ["no_cc"] }
strum = "0.16.0"
strum_macros = "0.16.0"

[dependencies.x25519-dalek]
version = "0.5"
default-features = false
features = ["std", "u64_backend"]

[dependencies.ed25519-dalek]
version = "1.0.0-pre.1"
default-features = false
features = ["std", "u64_backend"]

[dependencies.num-bigint]
version = "0.5"
features = ["rand", "i128", "u64_digit", "prime", "zeroize"]
package = "num-bigint-dig"

[dependencies.flate2]
version = "^1.0"
default-features = false
features = ["rust_backend"]

[dependencies.gperftools]
version = "0.2.0"
optional = true

[dependencies.buf_redux]
version = "0.8.1"
default-features = false

[dev-dependencies]
hex-literal = "^0.2"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
glob = "^0.3"
regex = "^1.1"
pretty_assertions = "0.6"
rand_xorshift = "0.1"
rand_chacha = "0.1"
pretty_env_logger = "0.3"

[features]
default = ["ringbuf"]
ringbuf = ["buf_redux/default"]
nightly = ["x25519-dalek/nightly", "ed25519-dalek/nightly", "rsa/nightly", "rand/nightly", "num-bigint/nightly", "clear_on_drop/nightly"]
avx2 = ["ed25519-dalek/avx2_backend"]
profile = ["gperftools"]
asm = ["sha-1/asm", "sha2/asm", "md-5/asm", "nightly"]
wasm = ["chrono/wasmbind", "nightly", "rand/wasm-bindgen"]

[profile.bench]
debug = true

[profile.release]
debug = 0
debug-assertions = false
opt-level = "s"
panic = "abort"


[workspace]
members = [
  "pgp-ffi"
]
