[package]
name = "pgp"
version = "0.1.0"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]
description = "PGP implementation in Rust"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/dignifiedquire/rpgp"
repository = "https://github.com/dignifiedquire/rpgp"

keywords = ["pgp", "gpg", "pretty good privacy", "email", "encryption"]


[dependencies]
num-bigint = { version = "0.3", features = ["rand", "i128", "u64_digit", "prime"] , package = "num-bigint-dig" }
crc24 = "^0.1"
base64 = { git = "https://github.com/dignifiedquire/rust-base64", branch = "fix/slow-writer" }
byteorder = "^1.2"
enum_primitive = "^0.1"
chrono = "^0.4"
failure = "^0.1"
circular = "^0.2"
sha-1 = "^0.8"
sha2 = "^0.8"
md-5 = "^0.8"
ripemd160 = "^0.8"
generic-array = "^0.12"
digest = "^0.8"
aes = "^0.3"
blowfish = "^0.4"
twofish = "^0.2"
des = "^0.3"
block-modes = "^0.3"
hex = "^0.3"
cfb-mode = "^0.3"
flate2 = { version = "^1.0", default-features = false, features = ["rust_backend"] }
num-derive = "0.2.3"
num-traits = "0.2.6"
cast5 = { git = "https://github.com/dignifiedquire/block-ciphers", branch = "cast5" }
x25519-dalek = { version = "0.5", default-features = false, features = ["std", "u64_backend"] }
ed25519-dalek = { version = "1.0.0-pre.1", default-features = false, features = ["std", "u64_backend"] }
lazy_static = "1.2.0"
block-padding = "0.1.2"
log = "0.4.6"
pretty_env_logger = "0.3"
buf_redux = { version = "0.8.1", default-features = false }
try_from = "^0.3"
derive_builder = "0.7.0"
bitfield = "0.13.1"
sha3 = "0.8.1"
rand = "0.6"

[dependencies.nom]
version = "^4.2"

[dependencies.gperftools]
version = "0.2.0"
optional = true

[dependencies.rsa]
version = "0.1.2"

[dev-dependencies]
hex-literal = "^0.1"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
glob = "^0.2"
regex = "^1.1"
pretty_assertions = "0.6"
rand_xorshift = "0.1.1"

[features]
default = []
nightly = ["x25519-dalek/nightly", "ed25519-dalek/nightly", "rsa/nightly", "asm", "rand/nightly", "buf_redux/default"]
avx2 = ["ed25519-dalek/avx2_backend"]
profile = ["gperftools"]
asm = ["sha-1/asm", "sha2/asm", "md-5/asm"]

[workspace]
members = [
  "pgp-ffi",
  "ios-simulator",
]
