[package]
name = "pgp-ffi"
version = "0.1.0"
homepage = "https://github.com/dignifiedquire/rpgp"
description = "PGP implementation in Rust"
authors = ["dignifiedquire <dignifiedquire@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
pgp = { path = "../" }
hex = "0.3.2"
libc = "0.2.49"

[build-dependencies]
cbindgen = "0.8"

# [profile.release]
# debuginfo = 0
# opt-level = "s"
# codegen-units = 1
# TODO: Enable these through the CLI when building
# panic = "abort"
# lto = "thin"

[features]
default = []
nightly = ["pgp/nightly"]