version: 2.1

executors:
  default:
    docker:
      - image: rustlang/rust:nightly
    working_directory: /mnt/crate

fast-checkout: &fast-checkout
  attach_workspace:
    at: /mnt

restore-cache: &restore-cache
  restore_cache:
    keys:
      - cargo-v2-{{ checksum "rust-toolchain" }}-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}-{{ arch }}

jobs:
  cargo_fetch:
    executor: default
    steps:
      - checkout
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - cargo-v2-{{ checksum "rust-toolchain" }}-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}-{{ arch }}
      - run: rustup install stable
      - run: rustup install $(cat rust-toolchain)
      - run: rustup default $(cat rust-toolchain)
      - run: rustup component add --toolchain $(cat rust-toolchain) rustfmt
      - run: rustup component add --toolchain $(cat rust-toolchain) clippy
      - run: cargo update
      - run: cargo fetch
      - run: rustc +stable --version
      - run: rustc +$(cat rust-toolchain) --version
      - persist_to_workspace:
          root: /mnt
          paths:
            - crate
      - save_cache:
          key: cargo-v2-{{ checksum "rust-toolchain" }}-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}-{{ arch }}
          paths:
            - $HOME/.cargo
            - $HOME/.rustup

  test:
    executor: default
    steps:
      - *fast-checkout
      - *restore-cache
      - run:
          name: Test (x86_64-unknown-linux-gnu)
          command: TARGET=x86_64-unknown-linux-gnu ci/run.sh
          no_output_timeout: 15m

  rustfmt:
    executor: default
    steps:
      - *fast-checkout
      - *restore-cache
      - run:
          name: Run cargo fmt
          command: cargo fmt --all -- --check

  clippy:
    executor: default
    steps:
      - *fast-checkout
      - *restore-cache
      - run:
          name: Run cargo clippy
          command: cargo clippy --all

  test_macos:
    macos:
      xcode: "10.0.0"
    working_directory: ~/crate
    steps:
      - run:
          name: Configure environment variables
          command: |
            echo 'export PATH="${HOME}/.cargo/bin:${HOME}/.bin:${PATH}"' >> $BASH_ENV
            echo 'export CIRCLE_ARTIFACTS="/tmp"' >> $BASH_ENV
      - checkout
      - run:
          name: Install Rust
          command: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: rustup install $(cat rust-toolchain)
      - run: rustup default $(cat rust-toolchain)
      - run: cargo update
      - run: cargo fetch
      - run:
          name: Test
          command: TARGET=x86_64-apple-darwin ci/run.sh

workflows:
  version: 2.1

  test:
    jobs:
      - cargo_fetch
      - rustfmt:
          requires:
            - cargo_fetch
      - clippy:
          requires:
            - cargo_fetch
      - test:
          requires:
            - cargo_fetch

      - test_macos:
          requires:
            - cargo_fetch
